name: ssj-develop
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.10
  - numpy = 1.26.0
  - scipy = 1.12.0
  - pandas = 2.1.1
  - numba = 0.60.0
  - pip = 24.3.1
  - matplotlib = 3.9.2
  - optimagic = 0.5.0
  - wquantiles = 0.6
  - setuptools
  - pip:
    - interpolation == 2.2.7
    - dfo-ls == 1.5.3

